name: CI/CD for K8s Inspector Service

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: k8s-inspector
  K8S_DEPLOYMENT_NAME: k8s-inspector

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-inspector:${{ github.sha }}
      
      - name: Update deployment manifest
        # ADDED: This step updates the image tag in your deployment file.
        # Assumes your file is located at 'kubernetes/deployment.yaml'.
        run: |
          sed -i "s|image: .*|image: yashwanthydg/k8s-inspector:${{ github.sha }}|g" kubernetes/manifest.yaml
  
      - name: Commit and push manifest changes
        # ADDED: This step commits the updated manifest file back to your main branch.
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kubernetes/manifest.yaml
          git diff --staged --quiet || git commit -m "CI: Update image tag to ${{ github.sha }}"
          git push

  deploy:
    name: Deploy to Kubernetes
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/k8s-inspector app=${{ secrets.DOCKERHUB_USERNAME }}/k8s-inspector:${{ github.sha }}
          echo "Deployment updated successfully!"
